name: build_and_pub_neon

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: neonlabsorg/gnosis-neon-ui
  DOCKERHUB_USERNAME: ${{secrets.DHUBU}}
  DOCKERHUB_PASSWORD: ${{secrets.DHUBP}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD

    - name: Tag and push Docker image
      run: |
        docker tag $IMAGE_NAME $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:latest
